name: main-build

#this drops to nuget

on:
  push:

  workflow_dispatch:

jobs:
  build:
    name: Build Reloadify3000
    env:
      NUPKG_MAJOR: 1.0.
      BASE: 8
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Reloadify3000
        run: |
          dotnet build /r /p:Configuration=Debug Reloadify3000/Reloadify3000.csproj  
          dotnet msbuild /r /p:Configuration=Debug Reloadify3000.Build/Reloadify3000.Build.Tasks.csproj

      - name: Nuget Pack step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR$MINOR_VERSION-beta
          echo "PACKAGE VERSION: $VERSION"
          nuget pack Reloadify3000.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg

      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact
          path: |
            **/*.nupkg
            **/*.snupkg
            **/*.symbols.nupkg

      - name: Build and pack VSMac extension
        run: |
          dotnet build /r /p:Configuration=Debug Reloadify3000/Reloadify3000.csproj  
          dotnet msbuild /r /t:Build /p:Configuration=Debug Reloadify.VSMac/Reloadify.VSMac.csproj /p:CreatePackage=true

      - uses: actions/upload-artifact@v2
        name: Upload VS Mac extension
        with:
          name: VSMac-extension
          path: |
            **/*.mpack

