name: main-build

#this drops to nuget

on:
  push:

  workflow_dispatch:

jobs:
  build:
    name: Build Reloadify3000
    env:
      NUPKG_MAJOR: 1.0.
      BASE: 8
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: install .NET
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
          & .\dotnet-install.ps1 -InstallDir "$env:ProgramFiles\dotnet\" -Verbose -Channel STS
          & dotnet --list-sdks

      - name: Build Reloadify3000
        run: |
          dotnet build /r /p:Configuration=Debug Reloadify3000/Reloadify3000.csproj  
          dotnet msbuild /r /p:Configuration=Debug Reloadify3000.Build/Reloadify3000.Build.Tasks.csproj

      - name: Nuget Pack step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR$MINOR_VERSION-beta
          echo "PACKAGE VERSION: $VERSION"
          nuget pack Reloadify3000.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg

      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact
          path: |
            **\*.nupkg
            **\*.snupkg
            **\*.symbols.nupkg
